# Generated by Django 2.1.4 on 2018-12-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181221_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
